version: 2
updates:
  - package-ecosystem: 'cargo'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'

  - package-ecosystem: 'npm'
    directory: '/packages/cli'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
