#!/usr/bin/env bash
# Creates a small JS monorepo fixture used by action-test.yml.
# Usage: setup-fixture.sh [--shards] [--isolate] [--change]
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"   # repo root
FIXTURE="$PWD/.fixture"
rm -rf "$FIXTURE"
mkdir -p "$FIXTURE/packages/app" "$FIXTURE/packages/core" "$FIXTURE/packages/shared" "$FIXTURE/packages/root-tool" "$FIXTURE/.yarn/releases"

cat > "$FIXTURE/package.json" << 'EOF'
{
  "name": "fixture-root",
  "private": true,
  "packageManager": "yarn@4.11.0",
  "workspaces": ["packages/*"],
  "dependencies": { "@fixture/root-tool": "workspace:*" },
  "scripts": { "verify-install": "node verify-install.js" }
}
EOF

cp "$ROOT/.yarn/releases/yarn-4.11.0.cjs" "$FIXTURE/.yarn/releases/"
cat > "$FIXTURE/.yarnrc.yml" << 'EOF'
nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.11.0.cjs
EOF
cat > "$FIXTURE/turbo.json" << 'EOF'
{ "tasks": { "test": { "outputs": [] } } }
EOF
cat > "$FIXTURE/yarn.lock" << 'EOF'
# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

"@fixture/app@workspace:packages/app":
  version: 0.0.0-use.local
  resolution: "@fixture/app@workspace:packages/app"
  dependencies:
    "@fixture/core": "workspace:*"
  languageName: unknown
  linkType: soft

"@fixture/core@workspace:*, @fixture/core@workspace:packages/core":
  version: 0.0.0-use.local
  resolution: "@fixture/core@workspace:packages/core"
  dependencies:
    "@fixture/shared": "workspace:*"
  languageName: unknown
  linkType: soft

"@fixture/shared@workspace:*, @fixture/shared@workspace:packages/shared":
  version: 0.0.0-use.local
  resolution: "@fixture/shared@workspace:packages/shared"
  languageName: unknown
  linkType: soft

"@fixture/root-tool@workspace:*, @fixture/root-tool@workspace:packages/root-tool":
  version: 0.0.0-use.local
  resolution: "@fixture/root-tool@workspace:packages/root-tool"
  languageName: unknown
  linkType: soft

"fixture-root@workspace:.":
  version: 0.0.0-use.local
  resolution: "fixture-root@workspace:."
  languageName: unknown
  linkType: soft
EOF

cat > "$FIXTURE/packages/app/package.json" << 'EOF'
{
  "name": "@fixture/app",
  "version": "1.0.0",
  "dependencies": { "@fixture/core": "workspace:*" },
  "scripts": { "test": "node -e \"require('fs').appendFileSync(process.env.FIXTURE_LOG || 'fixture.log', 'app:' + (process.env.NANOOM_SHARD_INDEX || '0') + '\\n')\"" }
}
EOF
echo "module.exports = { name: '@fixture/app' };" > "$FIXTURE/packages/app/index.js"

cat > "$FIXTURE/packages/core/package.json" << 'EOF'
{
  "name": "@fixture/core",
  "version": "1.0.0",
  "dependencies": { "@fixture/shared": "workspace:*" },
  "scripts": { "test": "node -e \"require('fs').appendFileSync(process.env.FIXTURE_LOG || 'fixture.log', 'core:' + (process.env.NANOOM_SHARD_INDEX || '0') + '\\n')\"" }
}
EOF
echo "module.exports = { name: '@fixture/core' };" > "$FIXTURE/packages/core/index.js"

cat > "$FIXTURE/packages/shared/package.json" << 'EOF'
{
  "name": "@fixture/shared",
  "version": "1.0.0",
  "scripts": { "test": "node -e \"require('fs').appendFileSync(process.env.FIXTURE_LOG || 'fixture.log', 'shared:' + (process.env.NANOOM_SHARD_INDEX || '0') + '\\n')\"" }
}
EOF
echo "module.exports = { name: '@fixture/shared' };" > "$FIXTURE/packages/shared/index.js"

cat > "$FIXTURE/packages/root-tool/package.json" << 'EOF'
{
  "name": "@fixture/root-tool",
  "version": "1.0.0",
  "main": "index.js"
}
EOF
cat > "$FIXTURE/packages/root-tool/index.js" << 'EOF'
module.exports = { rootDependency: true };
EOF

cat > "$FIXTURE/verify-install.js" << 'EOF'
const fs = require('fs');
const path = require('path');
const target = process.argv[2];
if (!target) throw new Error('usage: node verify-install.js <workspace>');
const rootTool = require('@fixture/root-tool');
if (!rootTool.rootDependency) throw new Error('root dependency was not installed');
const dependency = { '@fixture/app': '@fixture/core', '@fixture/core': '@fixture/shared' }[target];
if (dependency) {
  require(require.resolve(dependency, { paths: [__dirname] }));
}
console.log(`[fixture verify] root=@fixture/root-tool workspace=${target} dependency=${dependency || 'none'}`);
fs.writeFileSync(path.join(__dirname, 'install-verification.log'), `${target}\n`);
EOF

SHARD_BLOCK=""
ISOLATE_BLOCK=""
CHANGE=false
for arg in "$@"; do
  case "$arg" in
    --shards) SHARD_BLOCK=', "rules": [{ "name": "@fixture/shared", "shard": [{ "task": "test", "shard": 2 }] }]' ;;
    --isolate) ISOLATE_BLOCK=', "rules": [{ "name": "@fixture/app", "isolate": ["test"] }]' ;;
    --change) CHANGE=true ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

RULES=""
if [ -n "$SHARD_BLOCK" ]; then RULES="$SHARD_BLOCK"; fi
if [ -n "$ISOLATE_BLOCK" ]; then
  if [ -n "$RULES" ]; then
    RULES=', "rules": [{ "name": "@fixture/shared", "shard": [{ "task": "test", "shard": 2 }] }, { "name": "@fixture/app", "isolate": ["test"] }]'
  else
    RULES="$ISOLATE_BLOCK"
  fi
fi

if [ -n "$RULES" ]; then
  SHARD_BLOCK="${RULES%]}, { \"name\": \"@fixture/root-tool\", \"ignore\": true }]"
else
  SHARD_BLOCK=', "rules": [{ "name": "@fixture/root-tool", "ignore": true }]'
fi

cat > "$FIXTURE/nanoom.config.json" << EOF
{
  "group": {
    "ci": { "tasks": ["test"]${SHARD_BLOCK} }
  },
  "globalDependencies": ["*.lock"]
}
EOF

cd "$FIXTURE"
git init -q -b main
git config user.email fixture@example.com
git config user.name fixture
git add . ':!yarn.lock'
git commit -q -m init --no-gpg-sign
git add yarn.lock
git commit -q -m lockfile --no-gpg-sign
if [ "$CHANGE" = true ]; then
  git -C "$FIXTURE" switch -q -c feature
  printf 'fixture change\n' > "$FIXTURE/packages/shared/changed.txt"
  git -C "$FIXTURE" add packages/shared/changed.txt
  git -C "$FIXTURE" commit -q -m change --no-gpg-sign
fi
echo "Fixture ready at $FIXTURE"
