name: nanoom e2e

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  affected:
    name: affected
    runs-on: ubuntu-latest
    outputs:
      has_change: ${{ steps.calculate.outputs.has_change }}
      groups: ${{ steps.calculate.outputs.groups }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100
      
      - name: Calculate affected workspaces and matrix
        id: calculate
        uses: XionWCFM/nanoom/.github/actions/affected@v0.2.9

  matrix:
    name: Run ${{ matrix.name }}
    needs: affected
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.affected.outputs.groups).ci.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          
      - name: Enable Yarn 4
        run: corepack enable

      - name: Install fixture dependencies
        uses: XionWCFM/nanoom/.github/actions/install@v0.2.9
        with:
          packageManager: yarn 
          matrix: ${{ toJSON(matrix) }}

      - name: run
        uses: XionWCFM/nanoom/.github/actions/run@v0.2.9
        with:
          packageManager: yarn
          monorepoTool: turbo
          matrix: ${{ toJSON(matrix) }}
          group: ci


  status:
    name: status
    needs: [affected, matrix]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: XionWCFM/nanoom/.github/actions/status@v0.2.9
        with:
          needs: ${{ toJSON(needs) }}
        
